# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - clinicaDentalfunctions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-functions' # set this to the path to your Azure Functions project
  NODE_VERSION: '18.x' # use Node 18.x to match Azure Functions runtime v4 (LTS)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          popd

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # ensure artifact is downloaded into ./node-app by default; we'll copy the release.zip to workspace root next
          path: node-app

      - name: Show downloaded artifact files
        run: |
          echo "Workspace: $PWD"
          ls -la
          echo "Checking for node-app/release.zip or ./release.zip"
          if [ -f node-app/release.zip ]; then
            echo "release.zip found at node-app/release.zip"
            unzip -l node-app/release.zip
          elif [ -f release.zip ]; then
            echo "release.zip found at ./release.zip"
            unzip -l release.zip
          else
            echo "release.zip not found in workspace"
            find . -maxdepth 3 -type f -name "release.zip" -print || true
          fi

      - name: Prepare package for deployment
        run: |
          if [ -f node-app/release.zip ]; then
            cp node-app/release.zip ./release.zip
            echo "Copied node-app/release.zip -> ./release.zip"
          elif [ -f release.zip ]; then
            echo "release.zip already at ./release.zip"
          else
            echo "ERROR: release.zip not found; listing files:" && find . -maxdepth 4 -type f -name "release.zip" -print || true
            exit 1
          fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E6ECE572C45148E99B2291C2571AD010 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5641D6C65439479B81247A1CB96ED87E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50D034B703DD4C919E54FDACDE463690 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'clinicaDentalfunctions'
          slot-name: 'Production'
          package: ./release.zip